/**
 * 出典文言（引継書§4.6 verbatim定数）と共通メタ自動挿入（FR-C2/C3・N-7）。
 * 文言は指定どおりの逐語。改変禁止。
 */

export type SourceKey = 'edinet' | 'gbizinfo' | 'reinfolib' | 'houjin' | 'laws';

export const ATTRIBUTION_TEXT: Readonly<Record<SourceKey, string>> = {
  houjin:
    'このサービスは、国税庁法人番号システムのWeb-API機能を利用して取得した情報をもとに作成しているが、サービスの内容は国税庁によって保証されたものではない',
  reinfolib:
    'このサービスは、国土交通省不動産情報ライブラリのAPI機能を使用していますが、提供情報の最新性、正確性、完全性等が保証されたものではありません。',
  gbizinfo: '出典：経済産業省 Gビズインフォ',
  edinet: '出典：金融庁 EDINET',
  laws: '出典：e-Gov法令検索（デジタル庁）',
};

/** 法令英訳に付す参考訳disclaimer（FR-5 / 引継書§4.5） */
export const LAWS_TRANSLATION_DISCLAIMER =
  'This is an unofficial reference translation generated by machine. It has no legal effect and does not constitute legal advice. For official translations, see the Japanese Law Translation Database (JLT) by the Ministry of Justice.';

/** 全datasetアイテムに付与する共通メタ（FR-C2） */
export interface CommonMeta {
  source: SourceKey;
  source_url: string;
  retrieved_at: string;
  attribution: string;
  schema_version: string;
}

export interface CommonMetaInput {
  source: SourceKey;
  sourceUrl: string;
  schemaVersion: string;
  /** 省略時は現在時刻（ISO8601） */
  retrievedAt?: string;
}

/** アイテムへ共通メタを自動挿入する（N-7）。出典文言は SourceKey から必ず解決する。 */
export function withCommonMeta<T extends Record<string, unknown>>(
  item: T,
  input: CommonMetaInput,
): T & CommonMeta {
  return {
    ...item,
    source: input.source,
    source_url: input.sourceUrl,
    retrieved_at: input.retrievedAt ?? new Date().toISOString(),
    attribution: ATTRIBUTION_TEXT[input.source],
    schema_version: input.schemaVersion,
  };
}
